### ISSUE TITLE
Installation on raspberry pi 3B+

### ISSUE THREAD

**Issue by makerorne** [sourceryltd/makerhub-releases#2]
hello Kevin,

i am just a user of M2 for years and i have many problem to login to my machine.....
i use it with a Raspberry pi (v1..1.3 of makerverse) and now it is impossible for me to use my machine:
i have a message "network error" at login page... (internet is ok etc...)

i use PI to command my router with GPIO output (switch motor on at beginning and stop at end.... start vaccuum cleaner idem
and i tried to deactivate security with the line in makerverse file but it has no effect on my system (raspberry pi buster lite + makerverse 1.1.3)

So i tried to install your version; can you explain me how i must do ?
telll me if i am right:
1- install raspberry pi os lite 64 bits
2- make sudo apt update and sudo apt-get upgrade
3- upload your deb file
4- i install with command: sudo apt install Makerhub_1.2.0_amd64.deb

and after makerhub will be reachable on the lan ??
thanks for help and merry chrstmas !!

**Comment by kevinjohnson123** [comment]
sorry for the late reply.  one of our partner API providers no longer provides an API used in MakerHub.  We're working on a new version of makerhub.  Primarily only MacOS and Windows is supported.  In around 5-7 days i'll be adding a new version of MakerHub to the releases that fixes these problems.

**Comment by kevinjohnson123** [comment]
There's finally a version of makerhub v1.3.1 in the releases section.  if there are serial port problems open a new issue.

**Comment by makerorne** [comment]
hello Kevin,
i don't understand; i can install "appimage" on a raspberry pi ?
if yes can you juste explain me how ?
Thanks a lot for the help

Le mer. 27 mars 2024 à 09:10, kevinjohnson123 ***@***.***> a
écrit :
