### ISSUE TITLE
AppImage not available for versions beyond 1.2.0

### ISSUE THREAD

**Issue by nelmstr** [sourceryltd/makerhub-releases#3]
Can you please build an AppImage for makerhub for the newer versions?  I've been trying to get my M2 working since November, and none of the older versions have the newer calibration setup.

**Comment by kevinjohnson123** [comment]
> Can you please build an AppImage for makerhub for the newer versions? I've been trying to get my M2 working since November, and none of the older versions have the newer calibration setup.

I'll build an app image for   makerhub 1.3.0  today and reply to this thread when it's ready for download.

**Comment by kevinjohnson123** [comment]
> Can you please build an AppImage for makerhub for the newer versions? I've been trying to get my M2 working since November, and none of the older versions have the newer calibration setup.

the AppImage has been generated and uploaded and included in the build server for future builds.
check release  v1.3.1 for the download link
