### ISSUE TITLE
Error in Mini Frame X axis dimensions

### ISSUE THREAD

**Issue by Felixowns** [sourceryltd/makerhub-releases#4]
On a new install the M2 - Mini Frame default workspace has Xmin and Xmax both at -609.6mm

**Comment by kevinjohnson123** [comment]
> On a new install the M2 - Mini Frame default workspace has Xmin and Xmax both at -609.6mm

which version of  MakerHub ?   version 1.3.0 ?

**Comment by kevinjohnson123** [comment]
the problem has been fixed in  v1.3.1
