### ISSUE TITLE
Raspberry Pi 4B install

### ISSUE THREAD

**Issue by shiftylilbastrd** [sourceryltd/makerhub-releases#5]
I was wondering if work is still being done to get this over to raspberry pi 4b? I don't have a machine I can dedicate to my Maslow and since Makerverse stopped working for me months ago my machine is doing nothing for me except taking up space.

**Comment by lucapalazzo** [comment]
I hope there will be a RPI4 version, as it works well with 1.1.3 release and it's space and cost saving.

**Comment by kevinjohnson123** [comment]
it's a WIP.   There is a problem with the specific version of the Serial Port Library.  The problem has been identified and it's a matter of allocating time to deal with it.  There's a  Serial Port NodeJS library that is used, which requires a very specific version to be used with Makerhub's source tree.  The root problem is a Python version conflict.  For some reason the NodeJS build script doesn't want to see the  Python Virtual Environment.   So i'll need to revert to a build environment of Rasapian OS  that was still shipped with  Python 2.7.x and 3.x. 
If you know which specific build  or can direct me to a  Rasapian OS version that has both versions of Python  just drop me a link.  It will certainly save quite a bit of time.   Once i have the python problem dealt with it take very little time to build.

**Comment by shiftylilbastrd** [comment]
Quick google came up with this
http://www.intellamech.com/RaspberryPi-projects/python.html

**Comment by shiftylilbastrd** [comment]
Looks like Raspbian Jessie if you use the Desktop OS. If you’re trying to use Lite you have to install python 3. Only problem is Jessie is too old and won’t run on the RPI4.

**Comment by kevinjohnson123** [comment]
> Looks like Raspbian Jessie if you use the Desktop OS. If you’re trying to use Lite you have to install python 3. Only problem is Jessie is too old and won’t run on the RPI4.

it's only used as a build environment - not a runtime environment.   What happens during the NodeJS  build process is that the serial library requires a native binary, so it builds using the build scripts that are packaged with that NodeJS module.  Building on a Raspberry Pi3 B+ board will result in a  MakerHub debian installer that will run on a Raspberry pi4. 
Either way, i have a bit of free time that wasn't expected so i'll likely be able to setup this build environment tomorrow.

**Comment by shiftylilbastrd** [comment]
That’s great news. Glad I could help point you in the right direction. Can’t wait to get my Maslow up and running again.

**Comment by kevinjohnson123** [comment]
the Raspberry Pi 3B+  AppImage has been completed and uploaded to the Releases.  If there's any bugs in this version please open a new ticket.

**Comment by lucapalazzo** [comment]
Thank you very much, we will check it ASAP. BTW: Is it compatible with PI4B?

**Comment by kevinjohnson123** [comment]
closing this thread since there is a new build of makerhub 1.3.1  now

**Comment by kevinjohnson123** [comment]
> Thank you very much, we will check it ASAP. BTW: Is it compatible with PI4B?

it  _should_  run on any  debian based  ARM64  system.  This is the first time i was able to get it to build on  ARM,  so your mileage may vary.  It certainly needs thorough testing.

**Comment by shiftylilbastrd** [comment]
This still isn't working.
```
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```
When I run `dpkg -l` fuse is installed
```
ii  fuse3                                3.14.0-4                            arm64        Filesystem in Userspace (3.x version)
```

**Comment by lucapalazzo** [comment]
Hi, did you manage to make it work on RPI flawlessly? Can we help you in
some way?

Luca

**Comment by kevinjohnson123** [comment]
So far, i've only been able to get it to build on  Raspberry Pi3 B+.   Raspberry Pi 4 fails to build.  For now the easiest solution is to use a Raspberry Pi3 B+.   Maybe i should create a SD card image. That would probably solve any potential dependency problems.

**Comment by lucapalazzo** [comment]
Hi Kevin, any way to get it working on PI4?
